[package]
name = "phpdoc"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.1"

[dependencies]
ansi-to-tui = "7.0.0"
bat = { version = "0.25.0", default-features = false, features = [
  "regex-fancy",
] }
clap = { version = "4.5.35", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = { version = "0.29.0", default-features = false, features = [
  "derive-more",
  "events",
  "bracketed-paste",
] }
libxml = "0.3.3"
mago-interner = "0.22.2"
mago-names = "0.22.2"
mago-reference = "0.22.2"
mago-symbol-table = "0.9.1"
mago-token = "0.22.2"
quick-xml = { version = "0.37.4", features = ["async-tokio"] }
ratatui = "0.29.0"
tokio = { version = "1.44.2", features = ["macros", "fs", "rt-multi-thread"] }
